"""

Xpath stands for XML path language.

1. absolute (Full xpath)  # //html/body/div[1]/div/header/div[1]/div[1]/span/a/span/img
   and other way do mention X path is " Xpath = /html[1]/body[1]/div[1]/div[1]/header[1]/div[1]/div[1]/span[1]/a[1]/span[1]/img[1] "

2. relative (Partial xpath) # //*[@id="__next"]/div/header/div[1]/div[1]/span/a/span/img

3. This is generated by selector hub = /html[1]/body[1]/div[1]/div[1]/header[1]/div[1]/div[1]/span[1]/a[1]/span[1]/img[1]

4. X path with contains()
   It is widely used to check how many products are present with the same name. Ley say in a page, if we do have 4 computer products are present
   with the same name with the help of contains method we can figure out.

DOM - Document object Model



"""
import pytest
import time
from playwright.sync_api import Page, expect
def test_xpath_locators(page: Page):
    page.goto('https://row.gymshark.com/')

    #1. absolute xpath
    logo = page.locator("//html[1]/body[1]/div[1]/div[1]/header[1]/div[1]/div[1]/span[1]/a[1]/span[1]/img[1]")
    expect(logo).to_be_visible()
    page.wait_for_timeout(500)

    #2. Relative Xpath
    logo_1 = page.locator("//img[@alt='Gymshark']")
    expect(logo_1).to_be_visible()
    page.wait_for_timeout(500)

    #3.  xpath with contains()
    page.wait_for_timeout(500)
    page.goto('https://demowebshop.tricentis.com/')
    products = page.locator("//h2//a[contains(@href, 'computer')]")
    products_count = products.count() #4 count form 1
    print("Product count in web page:", products_count)
    expect(products).to_have_count(products_count)

    #The below example shows how to get the first and last element among the four.
    print("First Computer product:", products.first.text_content())
    print("Last Computer product:", products.last.text_content())
    print("n-th computer product:", products.nth(2).text_content()) #nth() takes from 0

    # To list all the product in the page
    product_title = products.all_text_contents()
    print("Product title:", product_title)

    print("Printing product titles using looping statement....")

    for i in product_title:
        print(i)
